Issue 545
ThinkBigAnalytics/AoaDockerComposeDemos pull request #53
Opened 2021-03-22 10:43 UTC by sulemanhasib43

https://github.com/ThinkBigAnalytics/AoaCoreService/issues/545 
Generalized docker-compose.yaml for multiple deployments and add traefik overrides.

2021-03-22 11:11 UTC, Christian-TD approved these changes
LGTM. Nice work!

2021-03-22 14:40 UTC, willfleury reviewed
Instead of creating another docker-compose file specifically for traefik, can we just update the docker-compose.yaml to use traefik. We want it working by default going forward so unless there is some reason not to add it there, it would be less maintenance

2021-03-26 20:38 UTC, Christian-TD requested changes

2021-03-26 20:38 UTC, Christian-TD commented on docker-compose.yaml
> +<<<<<<< HEAD
Watch out! fix these merge conflicts.

2021-03-29 03:23 UTC, sulemanhasib43 commented on docker-compose.yaml
> +<<<<<<< HEAD
yup fixed those. thanks man for looking out.

2021-03-30 18:27 UTC, sulemanhasib43 commented
@dartov this is tested with traefik/http and customisable env. Also thanks to @willfleury debugging s3 get recursive is also working now.

2021-03-30 18:30 UTC, sulemanhasib43 commented
we need a doc to explain .env, traefik, and how to deploy.

2021-03-30 18:31 UTC, sulemanhasib43 commented
We also need a https override .yaml for this. I will start working on it after discussion with @dartov .

2021-05-03 14:26 UTC, willfleury commented
@sulemanhasib43 @dartov what is the story with this branch? Can we merge it? I want to do the 4.0 release and it would be better to merge this first

2021-05-16 05:45 UTC, Christian-TD approved these changes

2021-05-16 05:47 UTC, Christian-TD approved these changes

2021-05-17 10:37 UTC, Christian-TD commented
@dartov @sulemanhasib43 please review it if you can so we can merge it. Thanks!

2021-05-20 14:22 UTC, dartov approved these changes
Just minor things, I'm fine merging this, worked for me

2021-05-20 14:22 UTC, dartov commented on docker-compose.yaml
> -        SHOW_INFERENCE_WORKFLOW: "false"
Why show inference workflow by default?

2021-05-20 14:22 UTC, dartov commented on .env
> +### Analytic Ops Configuration ###
typo :)

2021-05-20 14:22 UTC, dartov commented on docker-compose.yaml
>        - "61613:61613"
Don't need that port mapping anymore

2021-05-20 14:22 UTC, dartov commented on websites/landing/index.html
>              "tutorial": "http://localhost:8099/landing/help.html",
That needs to be http://home.aoa.local/landing/help.html

2021-05-20 14:22 UTC, dartov commented on README.md
> +# Analytic Ops Docker Compose Demo Stack Deployment
Typo :)

2021-05-20 14:22 UTC, dartov commented on README.md
> +# Analytic Ops Stack #
Typo :)

2021-05-20 15:01 UTC, willfleury commented on docker-compose.yaml
> -        SHOW_INFERENCE_WORKFLOW: "false"
I don't know why it was enabled by default but until a few commits ago on the UI it was. Saad made the change and now its disabled by default but for current 4.x release we still need this

2021-05-20 19:57 UTC, Christian-TD commented on README.md
> +# Analytic Ops Stack #
That was my cat playing with the keyboard XD

2021-05-20 20:08 UTC, Christian-TD commented on docker-compose.yaml
>        - "61613:61613"
nix'd

2021-05-20 20:12 UTC, merged